apiVersion: v1
kind: Service
metadata:
  name: django-crud-app-service
  labels:
    app: django-crud-app
spec:
  type: LoadBalancer
  selector:
    app: django-crud-app
  ports:
    - port: 8000
      targetPort: 8000